# Generated by Django 3.0.3 on 2021-02-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proect',
            new_name='Project',
        ),
    ]
